# Generated by Django 4.2 on 2023-12-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50)),
                ('artist_name', models.CharField(max_length=50)),
                ('album_image', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(default='name', max_length=50)),
                ('song_file', models.FileField(upload_to='songs')),
                ('picture', models.FileField(upload_to='picture')),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_in_album', to='music.album')),
                ('artist_name', models.ForeignKey(default='Artist', on_delete=django.db.models.deletion.CASCADE, related_name='songs_by_artist', to='music.album')),
            ],
        ),
    ]
